projects:
  awsapplication:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        graphQLApiId: 7gdmtbdzjjbcpaklidulyeejh4
      endpoints:
        prod: >-
          https://3bbunei3bzgtndyp7apgfmqciq.appsync-api.us-east-1.amazonaws.com/graphql
